name: Build

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Architecture"
        required: true
        default: "x86_64"
        type: choice
        options:
          - "arm"
          - "arm64"
          - "x86"
          - "x86_64"
      androidv:
        description: "Android Version"
        required: true
        default: "12.1"
        type: choice
        options:
          - "9"
          - "10"
          - "11"
          - "12.1"
          - "13"
      release:
        description: "Upload to release"
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Cache repository
        id: cache-repository
        uses: actions/cache@v3
        with:
          path: |
            vendor_gapps/*
            !vendor_gapps/out
          key: MindTheGapps-${{ hashFiles('**/packed-refs') }}
          restore-keys: MindTheGapps-

      - name: Map Android Version to tree
        run: |
          declare -A ANDROID_VER_MAP=([9]="pi" [10]="qoppa" [11]="rho" ["12.1"]="sigma" [13]="tau")
          ANDROID_VER=${ANDROID_VER_MAP[${{ github.event.inputs.androidv }}]}
          echo "ANDROIDV=$ANDROID_VER" >> $GITHUB_ENV
      - name: Clone repository
        if: steps.cache-repository.outputs.cache-hit != 'true'
        run: |
          rm -rf vendor_gapps
          git clone -b ${{ env.ANDROIDV }} --filter=tree:0 https://gitlab.com/MindTheGapps/vendor_gapps.git
      - name: Update repository
        if: steps.cache-repository.outputs.cache-hit == 'true'
        run: |
          cd ./vendor_gapps
          git restore .
          git clean -fxd
          git switch ${{ env.ANDROIDV }}
          git pull
      - name: Build
        run: |
          ANDROID_VER=${{ env.ANDROIDV }}
          cd ./vendor_gapps
          if [ -d overlay ]; then
            sudo apt-get install -y aapt zipalign
            mkdir -p common/proprietary/product/overlay
            sed -i -e '/overlay/d' ./build/gapps.sh
            sed -i -e '/RROs/d' ./build/gapps.sh
            keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -storepass android
            echo "Compiling RROs"
            find overlay -maxdepth 1 -mindepth 1 -type d -print0 | while IFS= read -r -d '' dir
            do
                echo "Building ${dir/overlay\//}"
                aapt package -M "$dir"/AndroidManifest.xml -S "$dir"/res/ -I /usr/local/lib/android/sdk/platforms/android-32/android.jar -F "${dir/overlay\//}".apk.u
                jarsigner -keystore debug.keystore "${dir/overlay\//}".apk.u androiddebugkey -storepass android
                zipalign 4 "${dir/overlay\//}".apk.u "${dir/overlay\//}".apk
            done
            mv *.apk common/proprietary/product/overlay
          fi
          make gapps_"${{ github.event.inputs.arch }}"
          DATA=$(date -u +%Y%m%d_%H%M%S)
          echo "artifact_name=Built_MindTheGapps-${{ github.event.inputs.androidv }}-${{ github.event.inputs.arch }}-$DATA" >> $GITHUB_ENV
      - name: Upload
        if: ${{ github.event.inputs.release != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: ./vendor_gapps/out/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.release == 'true' }}
        with:
          tag_name: ${{ github.event.inputs.androidv }}-${{ github.event.inputs.arch }}
          draft: true
          prerelease: true
          files: ./vendor_gapps/out/*

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
